# Generated by Django 3.1.7 on 2021-03-29 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('sobrenome', models.CharField(max_length=20)),
                ('idade', models.PositiveIntegerField(max_length=3)),
                ('data_nascimento', models.DateField()),
                ('email', models.CharField(max_length=40)),
                ('apelido', models.CharField(blank=True, max_length=20, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['nome', 'sobrenome'],
            },
        ),
    ]
