# Generated by Django 3.1.7 on 2021-04-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_auto_20210331_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(help_text='exemplo@contato.com', max_length=32, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='observacao',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Observação'),
        ),
    ]
