# Generated by Django 3.1.7 on 2021-04-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_auto_20210401_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(help_text='exemplo@contato.com', max_length=32, unique=True, verbose_name='E-mail'),
        ),
    ]
